services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: class_lib
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/src/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro

volumes:
  db_data:

